# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 060dac3fab1b73ad5cc5406e5b1fa93aa54429e745a7e1cd973accdf883d30245fb40082848a88b5b1d734f2846ac40adc9d78f3871a08a918036e7b6fc8a11f

test:
  secret_key_base: 3703030fe49e1333a073d9d8a38d69d68ff151ded5e8beb119d0f3e14530d0fbccefde3d0f80c5c74e12a8a5ae5c22e2d070f7343f4eeb4d31e36e74f402e597

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
